### ISSUE TITLE
Slow boot

### ISSUE THREAD

**Issue by brat002** [night-ghost/ardupilot#1]
#### Issue details
Speed of boot is slower than earlier. It takes about 30 secs. Sometime board boots fast 2-3 secs. The problem isn't reproducing every boot. FC doesn't answer on mavlink until blue led is flash.

#### Version
 b550b99

#### Platform
[х] Plane

#### Hardware type
Omnibus f4 v2 pro

#### Logs
Video: https://www.youtube.com/watch?v=8xuXnh26iv8

**Comment by night-ghost** [comment]
console log is required

**Comment by night-ghost** [comment]
no answer for a week, so closed
