### ISSUE TITLE
OSD RSSI not being displayed

### ISSUE THREAD

**Issue by Hwurzburg** [night-ghost/ardupilot#11]
#### Issue details
OSD does not display RSSI. Selecting either RSSI from FC or Ch8 has no effect...rssi always reads zero
#### Version
AirbotV2 00530022 34365116 34333836
ArduPlane V3.9.0-dev (fdd68fcd 2018-03-04 16:19:57

Airbot Omnibus F4 PRo V3

photo  and OSD file already provided in thread

**Comment by night-ghost** [comment]
yes I already know

**Comment by night-ghost** [comment]
fixed
