### ISSUE TITLE
How do I bulid code？

### ISSUE THREAD

**Issue by skyyuzhang** [night-ghost/ardupilot#13]
on ubuntu   how do i bulid it ?  I means  command  in Terminal   " make px4-v2"  ????   I want to tried it on my CC3D REV but I do not know how?  just get a  flash firmware.  where I could download builded firmware?   or  how to  build  code  on ubuntu  with  CC3D REV?  Thanks!!!!!!!

**Comment by night-ghost** [comment]
this is not issue but a support question. Ask it on [forum](https://www.rcgroups.com/forums/showthread.php?2784349-Ardupilot-on-OpenPilot-Revolution)
