### ISSUE TITLE
Arduplane  not work on Matek F405 CTR

### ISSUE THREAD

**Issue by sin5678** [night-ghost/ardupilot#15]
after flash the f4light_MatekF405_CTR_bl.dfu and f4light_MatekF405_CTR.dfu, board can not connect to MP,  Copter works will

**Comment by night-ghost** [comment]
this board is for copters, MatekF405-wing will be for plane

**Comment by Landflieger** [comment]
If the board only for copters, why building a plane-Version? 
IMHO the boards suits fine for planes, especially for wings...

**Comment by night-ghost** [comment]
by design of build scripts. I will check why it don't works but this is not a high priority task. 

RevoMini is best for both planes and copters, IMNSHO :)

**Comment by night-ghost** [comment]
Cool! 

>The board crashes when trying to initalize the I2C Device on bus 2

hmm, there was a lots of efforts to stop brute force bus scanning...

>Should I submit to the original Arduplilot or to your fork?

this depends on what you want to do, but even if you submit to original Ardupilot there will be request to me about your PR.

**Comment by night-ghost** [comment]
in new binaries
