### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by sin5678** [night-ghost/ardupilot#16]
clone from https://github.com/ArduPilot/ardupilot   , Run Rebuild.sh from /ardupilot/libraries/AP_HAL_F4Light/boards/f4light_MatekF405_CTR/support   ,errors as blow 

toolchain is gcc-arm-none-eabi-7-2017-q4-major

> 
> In file included from /home/xx/ardupilot/ArduCopter/../libraries//AP_HAL_F4Light/hardware/osd/osd.cpp:64:0:
> /home/xx/ardupilot/ArduCopter/../libraries//AP_HAL_F4Light/hardware/osd/osd_core/Panels.h: In function 'void OSDns::panSetup()':
> /home/xx/ardupilot/ArduCopter/../libraries//AP_HAL_F4Light/hardware/osd/osd_core/Panels.h:2871:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
>       osd_print_S(f);
>       ~~~~~~~~~~~^~~
> /home/xx/ardupilot/ArduCopter/../libraries//AP_HAL_F4Light/hardware/osd/osd_core/Panels.h:2874:2: note: here
>   case 0:
>   ^~~~
> /home/xx/ardupilot/ArduCopter/../libraries//AP_HAL_F4Light/hardware/osd/osd_core/Panels.h:2879:14: error: this statement may fall through [-Werror=implicit-fallthrough=]
>              k=10;
>              ~^~~
> /home/xx/ardupilot/ArduCopter/../libraries//AP_HAL_F4Light/hardware/osd/osd_core/Panels.h:2881:9: note: here
>          case 'b': // byte param
>          ^~~~
> /home/xx/ardupilot/ArduCopter/../libraries//AP_HAL_F4Light/hardware/osd/osd_core/Panels.h:2892:10: error: this statement may fall through [-Werror=implicit-fallthrough=]
>       offs=0x20;
>       ~~~~^~~~~
> /home/xx/ardupilot/ArduCopter/../libraries//AP_HAL_F4Light/hardware/osd/osd_core/Panels.h:2894:9: note: here
>          case 'c': // signed byte param
>          ^~~~
> /home/xx/ardupilot/ArduCopter/../libraries//AP_HAL_F4Light/hardware/osd/osd_core/Panels.h:2965:14: error: this statement may fall through [-Werror=implicit-fallthrough=]
>              k=10;
>              ~^~~
> /home/xx/ardupilot/ArduCopter/../libraries//AP_HAL_F4Light/hardware/osd/osd_core/Panels.h:2966:2: note: here
>   case 'z': // offset
>   ^~~~
> /home/xx/ardupilot/ArduCopter/../libraries//AP_HAL_F4Light/hardware/osd/osd_core/Panels.h:3016:11: error: this statement may fall through [-Werror=implicit-fallthrough=]
>        add =  0x10;
>        ~~~~^~~~~~~
> /home/xx/ardupilot/ArduCopter/../libraries//AP_HAL_F4Light/hardware/osd/osd_core/Panels.h:3017:6: note: here
>       case 'c':
>       ^~~~
> /home/xx/ardupilot/ArduCopter/../libraries//AP_HAL_F4Light/hardware/osd/osd.cpp: In function 'void OSDns::load_font()':
> /home/xx/ardupilot/ArduCopter/../libraries//AP_HAL_F4Light/hardware/osd/osd.cpp:661:25: error: this statement may fall through [-Werror=implicit-fallthrough=]
>                          if(last_c == 0x0d) continue;
>                          ^~
> /home/xx/ardupilot/ArduCopter/../libraries//AP_HAL_F4Light/hardware/osd/osd.cpp:664:21: note: here
>                      case 0x0d: // carridge return, end of line
>                      ^~~~
> In file included from /home/xx/ardupilot/ArduCopter/../libraries//AP_HAL_F4Light/hardware/osd/osd.cpp:64:0:
> /home/xx/ardupilot/ArduCopter/../libraries//AP_HAL_F4Light/hardware/osd/osd_core/Panels.h: At global scope:
> /home/xx/ardupilot/ArduCopter/../libraries//AP_HAL_F4Light/hardware/osd/osd_core/Panels.h:1493:13: warning: 'void OSDns::panWaitMAVBeats()' defined but not used [-Wunused-function]
>  static void panWaitMAVBeats(){
>              ^~~~~~~~~~~~~~~
> cc1plus: all warnings being treated as errors
> <builtin>: recipe for target '/home/xx/ardupilot/ArduCopter/../libraries//AP_HAL_F4Light/hardware/osd/osd.o' failed
> make: *** [/home/xx/ardupilot/ArduCopter/../libraries//AP_HAL_F4Light/hardware/osd/osd.o] Error 1

**Comment by night-ghost** [comment]
Do you really think that this toolchain is supported? Try gcc 4.9.3, or just add -Werror=implicit-fallthrough as GCC wish

**Comment by sin5678** [comment]
crazy old version 。。。。。。

**Comment by night-ghost** [comment]
feel free to redesign build system to what you want
