### ISSUE TITLE
Build fails for MatekF405-Wing

### ISSUE THREAD

**Issue by Landflieger** [night-ghost/ardupilot#21]
#### Issue details
at first an error for missing whitepace is thrown. You can rid of it by naming Board-Directory "MatekF405**_**Wing", building proceeds...

while building process some warnings are thrown "variable 'temp' set but not used"
ends up with following error:
/Users/pan/develeopment/night_ghost/ardupilot/ArduPlane/../libraries//AP_HAL_F4Light/hardware/hal/systick.c: In function 'error_throb':
/Users/pan/develeopment/night_ghost/ardupilot/ArduPlane/../libraries//AP_HAL_F4Light/hardware/hal/systick.c:106:24: error: 'HAL_GPIO_A_LED_PIN' undeclared (first use in this function)
     const uint8_t pin= HAL_GPIO_A_LED_PIN;
continuing by defining this pin compiling will go further until:
this warning appears:
/Users/pan/develeopment/night_ghost/ardupilot/ArduPlane/../libraries//AP_HAL_F4Light/hardware/hal/usart.c: In function 'usart_setup':
/Users/pan/develeopment/night_ghost/ardupilot/ArduPlane/../libraries//AP_HAL_F4Light/hardware/hal/usart.c:258:82: warning: suggest parentheses around arithmetic in operand of '|' [-Wparentheses]
     dev->regs->BRR = (uint16_t)tmpreg | ((((fractionaldivider * 8) + 50) / 100)) & ((uint8_t)0x07);
and the following error is thrown:
/Users/pan/develeopment/night_ghost/ardupilot/ArduPlane/../libraries//AP_HAL_F4Light/hardware/hal/adc.c: In function 'adc_init':
/Users/pan/develeopment/night_ghost/ardupilot/ArduPlane/../libraries//AP_HAL_F4Light/hardware/hal/adc.c:60:32: error: 'CR_CLEAR_MASK' undeclared (first use in this function)
     uint32_t tmp = ADC->CCR  & CR_CLEAR_MASK; // Clear MULTI, DELAY, DMA and ADCPRE bits
                                ^
/Users/pan/develeopment/night_ghost/ardupilot/ArduPlane/../libraries//AP_HAL_F4Light/hardware/hal/adc.c:60:32: note: each undeclared identifier is reported only once for each function it appears in
/Users/pan/develeopment/night_ghost/ardupilot/ArduPlane/../libraries//AP_HAL_F4Light/hardware/hal/adc.c:69:28: error: 'CR1_CLEAR_MASK' undeclared (first use in this function)
     tmp = dev->regs->CR1 & CR1_CLEAR_MASK;  // Clear RES and SCAN bits 
                            ^
/Users/pan/develeopment/night_ghost/ardupilot/ArduPlane/../libraries//AP_HAL_F4Light/hardware/hal/adc.c:74:26: error: 'CR2_CLEAR_MASK' undeclared (first use in this function)
   tmp = dev->regs->CR2 & CR2_CLEAR_MASK; // Clear CONT, ALIGN, EXTEN and EXTSEL bits 

#### Version
Latest commit f49bef4 6 hours ago

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
Plane

#### Hardware type
MatekF405-wing

#### Logs
no logging in build process, if its usefull I can tee the output

**Comment by Landflieger** [comment]
build for plane fails for Matek405-CTR too

**Comment by night-ghost** [comment]
fixed, should be OK now

**Comment by night-ghost** [comment]
sure, when I will got this board

**Comment by night-ghost** [comment]
fixed, binaries will be after testing
