### ISSUE TITLE
Please add target Matek F405-CTR

### ISSUE THREAD

**Issue by leonvuksic** [night-ghost/ardupilot#24]
#### Issue details

Please add support for Matek F405-CTR

**Comment by night-ghost** [comment]
was added some month ago

**Comment by leonvuksic** [comment]
Thank you <3 will flash this afternoon and test :)

**Comment by leonvuksic** [comment]
Can you please tell me which bin file I should flash for my fc?

**Comment by night-ghost** [comment]
surprise, f4light_MatekF405_CTR.*
