### ISSUE TITLE
Wrong pin definition in OMNIBUS V3

### ISSUE THREAD

**Issue by Landflieger** [night-ghost/ardupilot#25]
#### Issue details
Wrong pin definition in ardupilot/libraries/AP_HAL_F4Light/boards/f4light_OmnibusV3/board.h
Code

in CHIBIOS compatible layout, line 155 f:
# define HAL_BATT_VOLT_PIN      8 // ChibiOS compatible defines
# define HAL_BATT_CURR_PIN 8

#### Version
d28bac2

**Comment by night-ghost** [comment]
thanks, fixed, will be in next version
